### ISSUE TITLE
Error when running latest build

### ISSUE THREAD

**Issue by 0xf0xx0** [RedInquisitive/Haxa-Editor#4]
When trying to run the file java gives me this error:

```
› java /Users/gingkathfox/Documents/Haxa-Editor.jar            Documents
Exception in thread "main" java.lang.NoClassDefFoundError: /Users/gingkathfox/Documents/Haxa-Editor/jar
Caused by: java.lang.ClassNotFoundException: .Users.gingkathfox.Documents.Haxa-Editor.jar
	at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
```

**Comment by RedTopper** [comment]
I updated the release. Does the new binary work?

**Comment by 0xf0xx0** [comment]
nope, still broken, same error

**Comment by RedTopper** [comment]
Looks like you might be forgetting the `-jar` flag before the filename. Try that, and make sure you have java 8 installed. You should also just be able to double click it.

**Comment by 0xf0xx0** [comment]
now it gives me a version error:

```
› java -jar /Users/gingkathfox/Documents/Haxa-Editor.jar       Documents
Exception in thread "main" java.lang.UnsupportedClassVersionError: red/Editor : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)```

**Comment by RedTopper** [comment]
It looks like you might not be using Java 8, can you make sure you have any previous version uninstalled and install Java 8? If you have a newer version installed like Java 14, you should be able to have both versions installed at the same time.

You can get your version with `java -version`

**Comment by 0xf0xx0** [comment]
homerew tells me i have version 14, ill see if i can get v8

E: i grabbed the v8 download and uninstalled the homebrew version, still doesnt work

```
java version "1.6.0_65"
Java(TM) SE Runtime Environment (build 1.6.0_65-b14-468)
Java HotSpot(TM) 64-Bit Server VM (build 20.65-b04-468, mixed mode)
``` 

doesnt look like it changed either

**Comment by RedTopper** [comment]
Looks like you have Java 6 somewhere in your path. This is an example output:

```
C:\Users\ajwal\Git\Haxa-Editor>java -version
openjdk version "13.0.1" 2019-10-15
OpenJDK Runtime Environment AdoptOpenJDK (build 13.0.1+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 13.0.1+9, mixed mode, sharing)

C:\Users\ajwal\Git\Haxa-Editor>java -jar Haxa-Editor.jar
Now Starting Level Editor 2.0
...
```

Should also work with Java 8
```
C:\Users\ajwal\Git\Haxa-Editor>"C:\Program Files\AdoptOpenJDK\jdk-8.0.232.09-hotspot\bin\java.exe" -version
openjdk version "1.8.0_232"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_232-b09)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.232-b09, mixed mode)

C:\Users\ajwal\Git\Haxa-Editor>"C:\Program Files\AdoptOpenJDK\jdk-8.0.232.09-hotspot\bin\java.exe" -jar Haxa-Editor.jar
Now Starting Level Editor 2.0
...
```

You can find your corresponding Java versions using this:
```
C:\Users\ajwal\Git\Haxa-Editor>where java
c:\program files\adoptopenjdk\jdk-13.0.1.9-hotspot\bin\java.exe
c:\program files\adoptopenjdk\jdk-8.0.232.09-hotspot\bin\java.exe
```

**Comment by 0xf0xx0** [comment]
Figured it out, apparently macOS has its own built in java (which is 1.6), and the java updater doesnt replace the built-in command. It works now :3
